version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "testStackTYPES"
resolve_s3 = true
s3_prefix = "testStackTYPES"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = false
parameter_overrides = "Environment=prod TableName=testTableTYpes AwsRegion=us-east-1 NodeEnv=ssssss new=testVasssssslue"

[default.global.parameters]
region = "us-east-1"